LevelFive/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic import views



urlpatterns = [
    path(r'',views.index,name='index'),
    path('admin/', admin.site.urls),
    path(r'basic/',include('basic.urls'))
]

basic/urls.py
from django.conf.urls import url

from basic import views


app_name = 'basic'


urlpatterns = [
    url(r'register/',views.register,name='register')
]

basic/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
# Create your models here.



class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=CASCADE)

    # additional

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

    

basic/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import fields
from basic.models import UserProfileInfo

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

basic/views.py
from django.shortcuts import render
from basic.forms import UserForm
from basic.forms import UserProfileInfoForm

# Create your views here.


def index(request):
    return render(request,'basic/index.html')



def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        
        else:
            print(user_form.errors,profile_form.errors)
    
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basic/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

templates/basic/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base</title>
    <!--<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

</head>
<body>
    

    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">

                <li><a class="navbar-brand" href="{% url 'index' %}">django</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">admin</a></li>
                <li><a class="navbar-link" href="{% url 'basic:register' %}">register</a></li>



            </ul>


        </div>

        


    </nav>
    <div class="container">

        {% block body_block %}

        {% endblock %}



    </div>
    
</body>
</html>

templates/basic/index.html
{% extends 'basic/base.html' %}

{% block body_block %}

<div class="jumbotron">

    <h1>django level five</h1>

</div>

{% endblock %}

templates/basic/registration.html
{% extends 'basic/base.html' %}

{% load static %}

{% block body_block %}

<div class="jumbotron">

    {% if registered %}

    <h1>Thank you for registration</h1>

    {% else %}

    <h1>register here</h1>
    <h3>fill out the form</h3>

    <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}

        {{ user_form.as_p }}
        {{ profile_form.as_p }
    
    </form>

    {% endif %}


</div>


{% endblock %}